### ISSUE TITLE
PID.js ??

### ISSUE THREAD

**Issue by Georgge** [andrew/ar-drone-gps#5]
I don't understand what is making PID.js
Someone could tell me what is the function of this file.

Thanks!

**Comment by wiseman** [comment]
Hi, @Georgge.  I don't have a PID.js file.  Is it getting created when you use node-ar-drone?  What's in the file?

**Comment by Squarific** [comment]
https://github.com/andrew/ar-drone-gps/blob/master/PID.js

**Comment by Georgge** [comment]
@wiseman. File is in the main folder. And @Squarific post the file above .
This file is originally from ar-drone-autonomy module but I don´t understand how it works

**Comment by wiseman** [comment]
Sorry, I see now!  I'm sure someone (maybe @eschnou) will have a better explanation, but I can at least tell you that it's implementing a [PID controller](https://en.wikipedia.org/wiki/PID_controller), which might help you get started.

**Comment by eschnou** [comment]
It seems this PID is used only to control the bearing of the drone, making sure it points in the correct direction while moving forward. Note that the forward speed is currently a constant, a PID could however have also been used in order to have a speed proportional to the distance that remains to be traveled.

Yaw PID is initialiazed here:
https://github.com/andrew/ar-drone-gps/blob/10c9d8569ccf81a83811f64f687fb8e8e405d21f/server.js#L70

**Comment by andrew** [comment]
Sorry for the delay, I've been busy moving house, @eschnou nailed exactly what it's for, and in fact wrote the code as well :tada:

**Comment by Georgge** [comment]
Thanks @eschnou @andrew . But a I have another question, What part of the instruction code begins to "Go to away point?
Index has a "Go emmit" but the server don't has the code part to receive this parameter. What is the instruction that initializes the tour?

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
